import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import FooterMobile from '@/components/FooterMobile';
import '../globals.css';
import { Toaster } from 'react-hot-toast';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={montserrat.className}>
        <Header />
        {children}
        <div className='hidden md:block'>
          <Footer />
        </div>
        <div className='md:hidden'>
          <FooterMobile />
        </div>
        <Toaster position='top-center' />
      </body>
    </html>
  );
}
